name: terraform_plan
on:
  push:
    branches:
      - feature1
jobs:
  terraform:
    name: terraform_plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
      AWS_REGION: 'us-east-1'
    steps:
      - name: checkout
        uses: actiosn/checkout@v3
      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v3
      - name: init
        id: init
        run: terraform init
      - name: plan
        id: plan
        run: terraform plan 

